
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Categories
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  color text, -- CSS color code or class
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Products
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  stock integer default 0,
  category_id bigint references public.categories(id) on delete set null,
  is_weighable boolean default false, -- if true, might require weight input
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Customers (for "Fiado"/Credit)
create table public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  balance numeric(10,2) default 0, -- Positive means they owe money
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Transactions (Head)
create table public.transactions (
  id uuid default uuid_generate_v4() primary key,
  type text not null check (type in ('SALE', 'EXPENSE', 'MANUAL_ENTRY')),
  total_amount numeric(10,2) not null default 0,
  status text default 'COMPLETED', -- PENDING, COMPLETED, ANNULLED
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Transaction Items (Details)
create table public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id uuid references public.transactions(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null, -- Snapshot of name at time of sale
  quantity numeric(10,3) not null default 1,
  unit_price numeric(10,2) not null, -- Snapshot of price
  total_price numeric(10,2) not null
);

-- 6. Payments (Money Movement)
create table public.payments (
  id bigint generated by default as identity primary key,
  transaction_id uuid references public.transactions(id) on delete cascade,
  amount numeric(10,2) not null,
  method text not null check (method in ('CASH', 'TRANSFER', 'QR', 'CREDIT_CUSTOMER')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Seed Data (Categories)
insert into public.categories (name, color) values
('Panadería', 'bg-amber-200 text-amber-900'),
('Lácteos', 'bg-blue-100 text-blue-900'),
('Bebidas', 'bg-purple-100 text-purple-900'),
('Almacén', 'bg-gray-100 text-gray-900');

-- Insert Seed Data (Products)
insert into public.products (name, price, category_id, is_weighable) values
('Pan Felipe (kg)', 2500, 1, true),
('Medialunas (doc)', 6500, 1, false),
('Leche Entera 1L', 1500, 2, false),
('Coca Cola 2.25L', 2800, 3, false),
('Yerba Mate 500g', 3500, 4, false),
('Galletitas Variadas', 1200, 4, false);

-- Insert Seed Data (Customers)
insert into public.customers (name, balance) values
('Juan Pérez (Vecino)', 0),
('María Kiosco', 500);

-- Enable Row Level Security (RLS) - Recommended for Supabase
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;
alter table public.payments enable row level security;

-- Create Policies (Open for MVP - Modify for production!)
-- Allows anyone to read/write. In a real app, check auth.uid()
create policy "Allow public access" on public.categories for all using (true) with check (true);
create policy "Allow public access" on public.products for all using (true) with check (true);
create policy "Allow public access" on public.customers for all using (true) with check (true);
create policy "Allow public access" on public.transactions for all using (true) with check (true);
create policy "Allow public access" on public.transaction_items for all using (true) with check (true);
create policy "Allow public access" on public.payments for all using (true) with check (true);

