-- Bootstrap: estructura original del schema antes de las migrations 01+
-- Usa IF NOT EXISTS para ser idempotente en proyectos que ya corrieron schema.sql

create extension if not exists "uuid-ossp";

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  stock integer default 0,
  category_id bigint references public.categories(id) on delete set null,
  is_weighable boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- tabla legacy que migration 01 migrará a people y dropeará
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  balance numeric(10,2) default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.transactions (
  id uuid default uuid_generate_v4() primary key,
  type text not null check (type in ('SALE', 'EXPENSE', 'MANUAL_ENTRY')),
  total_amount numeric(10,2) not null default 0,
  status text default 'COMPLETED',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.transaction_items (
  id bigint generated by default as identity primary key,
  transaction_id uuid references public.transactions(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  quantity numeric(10,3) not null default 1,
  unit_price numeric(10,2) not null,
  total_price numeric(10,2) not null
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  transaction_id uuid references public.transactions(id) on delete cascade,
  amount numeric(10,2) not null,
  method text not null check (method in ('CASH', 'TRANSFER', 'QR', 'CREDIT_CUSTOMER')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;
alter table public.payments enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'categories' and policyname = 'Allow public access') then
    create policy "Allow public access" on public.categories for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'products' and policyname = 'Allow public access') then
    create policy "Allow public access" on public.products for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'customers' and policyname = 'Allow public access') then
    create policy "Allow public access" on public.customers for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'transactions' and policyname = 'Allow public access') then
    create policy "Allow public access" on public.transactions for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'transaction_items' and policyname = 'Allow public access') then
    create policy "Allow public access" on public.transaction_items for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'payments' and policyname = 'Allow public access') then
    create policy "Allow public access" on public.payments for all using (true) with check (true);
  end if;
end $$;
