
-- 1. Create 'people' table (unifies Customers and Providers)
create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  type text not null check (type in ('CLIENT', 'PROVIDER')),
  balance numeric(10,2) default 0, -- Positive = They owe us (Clients) or We owe them (Providers? TBD, KISS: always positive debt)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table public.people enable row level security;
create policy "Allow public access" on public.people for all using (true) with check (true);

-- 3. Migrate existing customers to people
insert into public.people (name, phone, balance, type)
select name, phone, balance, 'CLIENT' from public.customers;

-- 4. WARNING: We are about to drop 'customers'. 
-- Ensure your app code is updated to use 'people' before running this in production.
drop table public.customers;

-- 5. Add Seed Providers
insert into public.people (name, type) values 
('Distribuidora Coca Cola', 'PROVIDER'),
('Panadería Mayorista', 'PROVIDER');
