-- Tabla de configuración de unidades de venta (gramo, metro, litro, etc.)

create table if not exists public.units (
  id bigint generated by default as identity primary key,
  name text not null,
  symbol text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.units enable row level security;
create policy "Allow public access" on public.units for all using (true) with check (true);

-- Unidades por defecto
insert into public.units (name, symbol) values
  ('Unidad', 'u'),
  ('Gramo', 'g'),
  ('Kilogramo', 'kg'),
  ('Metro', 'm'),
  ('Centímetro', 'cm'),
  ('Litro', 'L'),
  ('Mililitro', 'ml'),
  ('Centímetro cuadrado', 'cm²'),
  ('Centímetro cúbico', 'cm³');

-- Añadir unit_id a productos (nullable: null = se vende por unidad)
alter table public.products
  add column if not exists unit_id bigint references public.units(id) on delete set null;

-- Migrar is_weighable -> unit_id (kg)
update public.products
set unit_id = (select id from public.units where symbol = 'kg' limit 1)
where is_weighable = true;

-- Eliminar columna antigua
alter table public.products drop column if exists is_weighable;
